language: russian
exclude: [vendor]
# Link to home
url: /

# link to github repo
github_editme_path: https://github.com/evotor/documentation-v2/tree/develop/

#feedback_email: ilytkin88@gmail.com
#feedback_subject_line: feedback subject line
feedback_disable: true

image_path: docs/images/
port: 4000
highlighter: rouge

highlighting_css: grey
# options: "monokai" (black), "syntax" (white), "darkly", "grey"
navbar_style: lighttheme-evoblue
navbar_logo: docs/images/logo_white.png

image_path: /docs/images/

javadoc: /javadoc

markdown: kramdown
kramdown:
 input: "GFM"
 auto_ids: true
 transliterated_header_ids: true
 hard_wrap: false
 syntax_highlighter: "rouge"
 toc_levels: '1,2'

collections:
  docs:
    output: true
  tags:
    output: false

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      topnav: topnav
      tag_group: taglist
  -
    scope:
      path: ""
      type: docs
    values:
      layout: default
      topnav: topnav
      tag_group: taglist
  -
    scope:
      path: ""
      type: tags
    values:
      layout: default
      topnav: topnav
      sidebar: taglist
      toc: false
      github_button: true
      search: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sidebar: evomain
      topnav: topnav

future: true

google_analytics: UA-84163503-7

#algolia:
#    application_id: 'EL1PU8ZHNW'
#    index_name:     'evotor-documentation'
#    search_only_api_key: 49a2a5eecb0954222a7f3390556e9581
#    record_css_selector: 'p,ul'
#    settings:
#    attributesToIndex:
#      - title
#      - h1
#      - h2
#      - h3
#      - h4
#      - h5
#      - h6
#      - unordered(text)
#      - unordered(tags)
#      - summary

exclude:
  - buildandpush.sh
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Jenkinsfile
  - jekyll.sh
  - README.md
  - tar_exclude
  - _docs/templates/
  - helm/

plugins:
#  - jekyll-algolia
#  - jekyll-remote-plantuml
########## UI text ###############


uistring:
  title: Документация Эвотор # Displays as site title on top nav bar and on site metadata
  description: Documentation theme for Jekyll websites  # Displays as site description meta
  search_placeholder_global: Поиск по сайту ...
  search_placeholder_product: Поиск по разделу ...
  minitoc_title: Содержание
  tags_title: Теги
  github_edit_button_text: Редактировать
  search_results_page_title: Результаты поиска
  search_no_results_found: Результатов не найдено.
  tag_terms:
    product: Product
    page: Page
    excerpt: Excerpt
    tag_page_intro: Страницы отмеченные тегом
